config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

  # get '/home/index', to: 'home#index'

  resources :tweets, only: :create
  
  get '/dashboard', to: 'dashboard#index'

  resources :usernames, only: [:new, :update]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user

  validates :body, presence: :true, length: {maximum: 280}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :tweets, dependent: :destroy

  validates :username, uniqueness: {case_sensitive: false}, allow_blank: true

  before_save :set_display_name, if: -> { username.present? && display_name.blank?}

  def set_display_name
    self.display_name = username.humanize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :redirect_to_username_form, if: -> {user_signed_in? && current_user.username.blank?}

    protected
    # Overwriting the sign_out redirect path method
    def after_sign_in_path_for(resource)
        dashboard_path
    end

    def redirect_to_username_form
        # return if controller_name == "usernames"
        redirect_to new_username_path
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
    before_action :authenticate_user!
    
    def index
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to dashboard_path if user_signed_in?
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!
    
    def create
        @tweet = Tweet.new(tweet_params.merge(user: current_user))

        if @tweet.save
            flash[:notice] = "Tweet saved successfully"
            redirect_to dashboard_path
        else
            flash[:danger] = "Tweet did not saved successfully"
            redirect_to dashboard_path
        end
    end

    private

    def tweet_params
        params.require(:tweet).permit(:body)
    end
end

app/controllers/usernames_controller.rb
class UsernamesController < ApplicationController
    before_action :authenticate_user!
    skip_before_action :redirect_to_username_form
    
    def new
    
    end

    def update
        current_user.update(username_params)
        redirect_to dashboard_path
    end

    def username_params
        params.require(:user).permit(:username, :display_name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/dashboard/index.html.erb
<div class="col-7">
    <div class="mb-3">
        <h5><%= link_to "Home", dashboard_path, class: "text-dark text-decoration-none" %></h5>
    </div>   
    
    <%= render "shared/tweet_form" %>

    <%= render Tweet.order(created_at: :desc) %>
    
    
</div>

<div class="col">
    Column 3
</div>

app/views/home/index.html.erb
<% if flash[:notice] %>
    <%= flash[:notice] %>
<% end %>

<% if user_signed_in? %>
 Time : <%= Time.now.to_date  %>
    
    <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>

<% else %>

<h1>Home#index</h1>

<%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %>
<%= link_to "Login", new_user_session_path, class: "btn btn-outline-primary" %>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CloneTwitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css">
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if user_signed_in? %>
      <div class="container py-2">
          <%= render 'shared/messages' %>
          <div class="row">
            
            <%= render 'shared/side_navbar' %>

            <%= yield %>
        </div>
      </div>

    <% else %>

      <%= yield %>
    <% end %>
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
  </body>
</html>

app/views/shared/_messages.html.erb
<% if flash[:notice] %>
        <div class="alert alert-success"><%= flash[:notice] %></div>
<% end %>

<% if flash[:danger] %>
    <div class="alert alert-danger"><%= flash[:danger] %></div>
<% end %>

app/views/shared/_side_navbar.html.erb
<aside class="col side-navbar">

    <%= link_to root_path, class: "d-flex align-items-center fs-4 mb-3 px-2" do %>
        <div class="px-3 py-3 rounded-circle">
            <span class="me-4 position-relative" style="bottom: 3x;"><%= image_tag "twitter.png", width: "32" %></span>
        </div>
    <% end %>

    <%= link_to root_path, class: "d-flex align-items-center fs-4 mb-2" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3x;"><%= image_tag "home.png", width: "32" %> Home</span>
        </div>
    <% end %>

    <%= link_to root_path, class: "d-flex align-items-center fs-4 mb-2" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3x;"><%= image_tag "notifications.png", width: "32" %> Notifications</span>
        </div>
    <% end %>

    <%= link_to root_path, class: "d-flex align-items-center fs-4 mb-2" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3x;"><%= image_tag "messages.png", width: "32" %> Messages</span>
        </div>
    <% end %>

    <%= link_to root_path, class: "d-flex align-items-center fs-4 mb-2" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3x;"><%= image_tag "bookmarks.png", width: "32" %> Bookmarks</span>
        </div>
    <% end %>

    <%= link_to root_path, class: "d-flex align-items-center fs-4 mb-2" do %>
        <div class="px-4 py-2 rounded-pill">
            <span class="me-4 position-relative" style="bottom: 3x;"><%= image_tag "user.png", width: "32" %> Profile</span>
        </div>
    <% end %>

    <div class="px-4">
        <%= button_tag "Tweet", type:"button", class: "btn btn-primary", data: { toggle: "modal", target: "#exampleModal" } %>
    </div>

    <div class="px-4">
        <%= button_to "Logout", destroy_user_session_path, method: :delete, class: "btn btn-outline-danger my-4" %>

    </div>
</aside>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        
        <button type="button" class="close m-0 p-0" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= render "shared/tweet_form" %>
      </div>
      
    </div>
  </div>
</div>

app/views/shared/_tweet_form.html.erb
<%= form_with model: Tweet.new, url: tweets_path, data: { turbo:false } do |f| %>    
    <div class="form-group">
        <%= f.text_area :body, placeholder: "What is happening?!" ,class: "form-control border-0" %>
    </div>
    <hr/>
    <p class="d-flex justify-content-end">
        <%= f.submit 'Tweet', class: 'btn btn-primary px-4 rounded-pill text-white font-weight-bold' %>
    </p>
<% end %>

app/views/tweets/_tweet.html.erb
<div class="single_tweet py-3 px-4">
                
    <% if (Time.now - tweet.created_at) > 1.day %>
        <p> @<%= tweet.user.username %> - <%= tweet.created_at.strftime("%B %d") %> </p>
    <% else %>
        <p> @<%= tweet.user.username %> - <%= time_ago_in_words(tweet.created_at) %> </p>

    <% end %>

    <p><%= tweet.body %></p>
</div>

app/views/usernames/new.html.erb
<div class="col-7 mt-3">
    
      <h2>Set your Username</h2>

      <%= form_with model: current_user, url: username_path(current_user) do |f| %>

        <div class="field mb-3">
          <%= f.label :username %><br />
          <%= f.text_field :username, autofocus: true, class: "form-control" %>
        </div>

        <div class="field mb-3">
          <%= f.label :display_name %><br />
          <%= f.text_field :display_name, class: "form-control" %>
        </div>

        <div class="actions">
          <%= f.submit "Set Username", class: "btn btn-primary" %>
        </div>
      <% end %>
    
</div>

<div class="col">
    Column 3
</div>